### ISSUE TITLE
Upgrade to 0.10.13 breaks encoding with JCS_YCbCr colorspace + CbCr420 chroma subsampling

### ISSUE THREAD

**Issue by tyranron** [kornelski/mozjpeg-sys#23]
The code like this:
```rust
let mut encoder = Compress::new(mozjpeg::ColorSpace::JCS_RGB);
encoder.set_mem_dest();
encoder.set_size(width, height);

encoder.set_color_space(mozjpeg::ColorSpace::JCS_YCbCr);
{
    let mut comp = encoder.components_mut();
    let (h, v) = ChromaSubsampling::CbCr420.into_jpeg_chroma_sampling_factors();  // Self::CbCr420 => (2, 2),
    // 0 - Y, 1 - Cb, 2 - Cr, 3 - K
    comp[1].h_samp_factor = h;
    comp[1].v_samp_factor = v;
    comp[2].h_samp_factor = h;
    comp[2].v_samp_factor = v;
}

// set luma/chroma qtables, quality, etc...

encoder.start_compress();
let _ = encoder.write_scanlines(&image);
encoder.finish_compress();
```
works like a charm on 0.10.12 and below.

But upgrading to 0.10.13 panics with the message:
```
libjpeg fatal error: Sampling factors too large for interleaved scan
```

Looking [at the code](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/8e895c79e1d4c2a6727ee5729fe88bba1051ce33/jcmaster.c#L408-L423), it seems that [`C_MAX_BLOCKS_IN_MCU` is overflowed](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/8e895c79e1d4c2a6727ee5729fe88bba1051ce33/jcmaster.c#L408-L423). Also because trying to use other less efficient subsampling schemes like `CbCr440` (factors `1 x 2`), or `CbCr444` (factors `1 x 1`) works OK.

Inspecting preset values gives no difference between versions:
```rust
panic!("-> {}x{} | {}x{} | {}x{}", comp[0].h_samp_factor, comp[0].v_samp_factor, comp[1].h_samp_factor, comp[1].v_samp_factor, comp[2].h_samp_factor, comp[2].v_samp_factor);
// -> 2x2 | 1x1 | 1x1
``` 

So, seems that `C_MAX_BLOCKS_IN_MCU` should have been overflowed in previous versions too. But does that mean we cannot use `CbCr420` subsampling?

**Comment by kornelski** [comment]
420 subsampling should still work.

The update includes newer libjpeg-turbo, so it's possible that it's stricter about configuration and checks for things it haven't checked before.

Now the question is:

* is this a bug in Rust wrapper for mozjpeg?
* is this a bug in C mozjpeg?
* is this a bug in libjpeg-turbo?

Are you able to reproduce the issue using low-level C API?

**Comment by tyranron** [comment]
@kornelski I've prepared the MRE in a separate repo to be able to play with it around: https://github.com/tyranron/mozjpeg-sys-issue-23-example

**Comment by kornelski** [comment]
I've looked into it, and I think this is not a bug. libjpeg-turbo merely started checking invalid inputs.

You've set invalid sampling. The default is 2,1,1 and you're changing it to 2,2,2, which doesn't make sense. You should set 2,1,1 for chroma-subsampled, or 1,1,1 for non-subsampled.

These values are numbers of samples, not number of pixels, so they're inverse of how channels look like.

**Comment by tyranron** [comment]
@kornelski hmmm... previously I've used the following mapping:

```rust
    pub fn into_jpeg_chroma_sampling_factors(self) -> (i32, i32) {
        match self {
            Self::CbCr444 => (1, 1),
            Self::CbCr422 => (2, 1),
            Self::CbCr440 => (1, 2),
            Self::CbCr420 => (2, 2),
            Self::CbCr411 => (4, 1),
        }
    }
```

Turns out, I was wrong. Would you be so kind to help me with their correction? Can't really grasp it.

So, if `1,1,1` means no subsampling, then it's [`CbCr444`](https://en.wikipedia.org/wiki/Chroma_subsampling#4:4:4). Then the default `2,1,1` seems to be [`CbCr422`](https://en.wikipedia.org/wiki/Chroma_subsampling#4:2:2). So, how [`CbCr420`](https://en.wikipedia.org/wiki/Chroma_subsampling#4:2:0) should look like?

![sub](https://i.stack.imgur.com/BSHpC.jpg)

How can I map `mozjpeg` sampling factors to the picture above?

**Comment by tyranron** [comment]
Is it like this?

- `4:4:4` (full horizontal, full vertical)
    ```rust
    comp[0].h_samp_factor = 1;  // Y
    comp[0].v_samp_factor = 1;  // Y
    comp[1].h_samp_factor = 1;  // Cb
    comp[1].v_samp_factor = 1;  // Cb
    comp[2].h_samp_factor = 1;  // Cr
    comp[2].v_samp_factor = 1;  // Cr
    ```

- `4:2:2` (1/2 horizontal, full vertical)
    ```rust
    comp[0].h_samp_factor = 2;  // Y
    comp[0].v_samp_factor = 1;  // Y
    comp[1].h_samp_factor = 1;  // Cb
    comp[1].v_samp_factor = 1;  // Cb
    comp[2].h_samp_factor = 1;  // Cr
    comp[2].v_samp_factor = 1;  // Cr
    ```

- `4:1:1` (1/4 horizontal, full vertical)
    ```rust
    comp[0].h_samp_factor = 4;  // Y
    comp[0].v_samp_factor = 1;  // Y
    comp[1].h_samp_factor = 1;  // Cb
    comp[1].v_samp_factor = 1;  // Cb
    comp[2].h_samp_factor = 1;  // Cr
    comp[2].v_samp_factor = 1;  // Cr
    ```

- `4:2:0` (1/2 horizontal, 1/2 vertical)
    ```rust
    comp[0].h_samp_factor = 2;  // Y
    comp[0].v_samp_factor = 2;  // Y
    comp[1].h_samp_factor = 1;  // Cb
    comp[1].v_samp_factor = 1;  // Cb
    comp[2].h_samp_factor = 1;  // Cr
    comp[2].v_samp_factor = 1;  // Cr
    ```

**Comment by kornelski** [comment]
Yeah, that looks correct.
