### ISSUE TITLE
Upgrade nasm-rs to 0.2.4

### ISSUE THREAD

**Issue by jpalus** [kornelski/mozjpeg-sys#29]
Would you please consider upgrading nasm-rs to version >= 0.2.4 which ships with x32 ABI support?

**Comment by kornelski** [comment]
This crate specifies nasm `version = "0.2.0"`, which in Cargo means `0.2 or later`, so it's already using 0.2.4. Run `cargo update`.

**Comment by jpalus** [comment]
Admittedly I don't really know how cargo dependencies work but my main goal is to assure that next release of dssim transitively depends on nasm 0.2.4. If that's gonna happen automatically than feel free to close the issue.
