### ISSUE TITLE
When using msvc the boolean definition is wrong.

### ISSUE THREAD

**Issue by uttarayan21** [kornelski/mozjpeg-sys#32]
When using the msvc toolchain for compiling mozjpeg-sys.
If a another crate uses `jpeglib.h`
and has `#define HAVE_BOOLEAN  1` 
and `#include <windows.h>`
Then there's a size mismatch in `jpeg_decompress_struct`
since by default it's compiled using 
`typedef int boolean`
where as `windows.h` defines it as 
`typedef unisgned char boolean`

AFAIK this is not an issue when using the gnu toolchain for windows.

**Comment by kornelski** [comment]
Is there a bug here?

As far as I can tell, this crate's build doesn't include `<windows.h>` and doesn't define `HAVE_BOOLEAN`, so it's going to always have libjpeg's default ABI with `boolean` equal to `int`.

**Comment by uttarayan21** [comment]
I think there's a bug here.
So what I'm doing is making bindings over libraw.


In build.rs libraw includes `<window.h>`
So I have to `#define HAVE_BOOLEAN`
To not let mozjpeg overwrite the `typedef unisgned char boolean` from windows

Then when libraw calls
`jpeg_create_decompress(&cinfo)`
What ends up happening is
That gets expanded to
`jpeg_CreateDecompress(&cinfo, JPEG_LIB_VERSION, sizeof(jpeg_decompress_struct))`

But since `jpeg_decompress_struct` includes a `boolean` type.
the size in the macro is evaluated using the smaller boolean type.
But since mozjpeg is compiled using int as the definition of boolean the size of `jpeg_decompress_struct` is larger 
so this evaluation fails
https://github.com/mozilla/mozjpeg/blob/af265e756233d2ec968da7a566d008ab31618cf4/jdapimin.c#L42
