### ISSUE TITLE
Questions about yanked 1.x releases

### ISSUE THREAD

**Issue by eric-seppanen** [kornelski/mozjpeg-sys#39]
Today cargo-deny alerted me to the fact that some mozjpeg-sys 1.x releases were yanked.

I came here hoping to find out if this was a security issue, or what the reason was. I wasn't able to find the issue- can someone tell me what the reason was?

Also, I don't see tags for the 1.1.0 and 1.1.1 releases. Is that source available in this repository?

**Comment by kornelski** [comment]
Rust is about to stabilize c-unwind feature that will break all old releases of the crate.

**Comment by eric-seppanen** [comment]
And what about the code for 1.1.x? Is that in another branch somewhere?

**Comment by kornelski** [comment]
I strongly suggest updating to the latest version. 

I'm not maintaining anything older, don't keep track of old branches, and I'm not releasing any soundness/bug/security fixes for anything other than the latest version.

**Comment by eric-seppanen** [comment]
> [I] don't keep track of old branches

I think that's unwise. Think about it from the perspective of a project that wants to know the provenance of their dependencies (a good idea for security and license compliance). Not publishing the branch the release came from doesn't send a good message.

**Comment by kornelski** [comment]
There's no technical guarantee that a GitHub branch or tag is related to code in a published crate. If you review code that is on GitHub, I can easily sneak malware past your reviews. 

Tarballs uploaded to crates.io are an independent copy, have an easy to forge and difficult to verify vcs metadata.

**Comment by eric-seppanen** [comment]
I am aware of the issues and hope that in the future there will be better tools to monitor crates that diverge from the source repository.

I don't think that withholding the 1.x source branch does anything to improve the situation.

**Comment by kornelski** [comment]
I see no value in maintaining a branch of outdated broken code, for which the only valid fix is the one that has already been made, the same exact that turned it into 2.0 due to the necessary ABI change.

1.x is not special in any way other than having unfixed Undefined Behavior, which is about to get aggressively blocked by the Rust compiler in 3 days.

In fact not having this branch is an important signal about irreversibility of the change, lack of choice on the matter, and yanking is to underscore urgency and seriousness of the situation.

**Comment by eric-seppanen** [comment]
I went looking for the history of 1.1.x because the 1.0.x releases were yanked, leading to warnings from `cargo deny` which I have configured to warn me about yanked releases. At the time the 1.1.x releases were still published and not yanked, so as far as I could tell that was still a viable upgrade path for old codebases.

It looks like the 1.1.x releases have now been yanked as well, which makes the request moot.

**Comment by ktecho** [comment]
I'm having the same problem. I'm trying to use `nokhwa`, which depends on `mozjpeg v0.9.8`, which gives this:

```
error: failed to select a version for the requirement `mozjpeg-sys = "^1.1"`
candidate versions found which didn't match: 2.2.0, 2.1.0, 2.0.6, ...
location searched: crates.io index
required by package `mozjpeg v0.9.8 (https://github.com/ImageOptim/mozjpeg-rust?tag=v0.9.8#13f59310)`
```

So we have here in the git the tag 1.0.6, and then 1.2, but none of the 1.1.x branch.

**Comment by kornelski** [comment]
All crates using MozJPEG must be updated to use the latest version. 

If a crate requests the old buggy version, notify crate maintainers they must urgently upgrade and release a new version of their crate.
